export const SEARCH_REPOS = 'SEARCH_REPOS'
export const SEARCH_REQUEST_SENT = 'SEARCH_REQUEST_SENT'
export const SEARCH_REQUEST_SUCCESS = 'SEARCH_REQUEST_SUCCESS'
export const SEARCH_REQUEST_FAIL = 'SEARCH_REQUEST_FAIL'
